project:
  type: website
website:
  title: handwriterApp
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/CSAFE-ISU/handwriterApp
        aria-label: handwriterApp GitHub
  sidebar:
    collapse-level: 1
    contents:
      - text: Home
        file: index.qmd
      - section: Reference
        contents:
          - text: handwriterApp
            file: man/handwriterApp.qmd
          - text: templateKeight
            file: man/templateKeight.qmd
          - text: templateKforty
            file: man/templateKforty.qmd
      - text: News
        file: NEWS.md
      - text: License
        file: LICENSE.md
      - text: Citation
        file: CITATION.md
format:
  html:
    css: styles.css
    toc: true
