project:
  type: website
website:
  navbar:
    background: white
    logo: CSAFE_Tools_handwriter.png
    search: true
    left:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd
      - text: Contact
        file: contact.qmd
      - text: News
        file: NEWS.md
      - text: License
        file: LICENSE.md
    right:
      - icon: github
        href: https://github.com/CSAFE-ISU/handwriterApp
        aria-label: handwriterApp GitHub
format:
  html:
    css: csafe.css
    toc: true
    toc-location: left
