project:
  type: website
website:
  title: handwriter
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/CSAFE-ISU/handwriterApp
        aria-label: handwriterApp GitHub
format:
  html:
    theme: csafe.scss
