project:
  type: website

website:
  title: "handwriterAppSite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    css: styles.css
    toc: true

editor: visual

